name: Cypress Tests

on: push

jobs:
  regression:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Cypress
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      - name: Run regression
        run: npm run cy:run:regression